// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wyifnscovwnfdmizyunl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind5aWZuc2NvdnduZmRtaXp5dW5sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk3ODIxODksImV4cCI6MjA4NTM1ODE4OX0.9jGmLTa59nkvwU8dxBTspQ6iAH7awCmTnmvk3odJ2H8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});